POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "abcd@b.com",
    "username": "a",
    "password": "Abcd1234",
    "firstName": "A",
    "lastName": "B"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "identifier": "abcd@b.com",
    "password": "Abcd1234"
}

###
POST http://localhost:3000/auth/check-username
Content-Type: application/json

{
    "username": "a"
}

###
POST http://localhost:3000/auth/check-email
Content-Type: application/json

{
    "email": "abcd@b.com"
}

###
